CREATE TABLE `diariobase` (
  `idhead` int(11) NOT NULL DEFAULT '0',
  `iddiariobase` int(11) NOT NULL AUTO_INCREMENT,
  `tipreg` smallint(6) DEFAULT NULL,
  `datapreg` timestamp NULL DEFAULT NULL,
  `codbdi` varchar(2) DEFAULT NULL,
  `codneg` varchar(12) DEFAULT NULL,
  `tpmerc` smallint(6) DEFAULT NULL,
  `nomres` varchar(12) DEFAULT NULL,
  `especi` varchar(10) DEFAULT NULL,
  `prazot` varchar(3) DEFAULT NULL,
  `modref` varchar(4) DEFAULT NULL,
  `preabre` decimal(13,2) DEFAULT NULL,
  `premax` decimal(13,2) DEFAULT NULL,
  `premin` decimal(13,2) DEFAULT NULL,
  `premed` decimal(13,2) DEFAULT NULL,
  `preult` decimal(13,2) DEFAULT NULL,
  `preofc` decimal(13,2) DEFAULT NULL,
  `preofv` decimal(13,2) DEFAULT NULL,
  `totneg` int(11) DEFAULT NULL,
  `quatot` bigint(20) DEFAULT NULL,
  `voltot` decimal(18,2) DEFAULT NULL,
  `preexe` decimal(13,2) DEFAULT NULL,
  `indopc` smallint(6) DEFAULT NULL,
  `datven` timestamp NULL DEFAULT NULL,
  `fatcot` int(11) DEFAULT NULL,
  `ptoexe` decimal(13,6) DEFAULT NULL,
  `codisi` varchar(12) DEFAULT NULL,
  `dimes` smallint(6) DEFAULT NULL,
  `head_idhead` int(11) DEFAULT NULL,
  PRIMARY KEY (`iddiariobase`)
) ENGINE=InnoDB AUTO_INCREMENT=177982 DEFAULT CHARSET=utf8;
